# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.4/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/saadberrada/Desktop/Rtype

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/saadberrada/Desktop/Rtype

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/saadberrada/Desktop/Rtype/CMakeFiles /Users/saadberrada/Desktop/Rtype//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/saadberrada/Desktop/Rtype/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MySFMLProject

# Build rule for target.
MySFMLProject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MySFMLProject
.PHONY : MySFMLProject

# fast build rule for target.
MySFMLProject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/build
.PHONY : MySFMLProject/fast

ecs/AComponent.o: ecs/AComponent.cpp.o
.PHONY : ecs/AComponent.o

# target to build an object file
ecs/AComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/AComponent.cpp.o
.PHONY : ecs/AComponent.cpp.o

ecs/AComponent.i: ecs/AComponent.cpp.i
.PHONY : ecs/AComponent.i

# target to preprocess a source file
ecs/AComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/AComponent.cpp.i
.PHONY : ecs/AComponent.cpp.i

ecs/AComponent.s: ecs/AComponent.cpp.s
.PHONY : ecs/AComponent.s

# target to generate assembly for a file
ecs/AComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/AComponent.cpp.s
.PHONY : ecs/AComponent.cpp.s

ecs/Core.o: ecs/Core.cpp.o
.PHONY : ecs/Core.o

# target to build an object file
ecs/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/Core.cpp.o
.PHONY : ecs/Core.cpp.o

ecs/Core.i: ecs/Core.cpp.i
.PHONY : ecs/Core.i

# target to preprocess a source file
ecs/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/Core.cpp.i
.PHONY : ecs/Core.cpp.i

ecs/Core.s: ecs/Core.cpp.s
.PHONY : ecs/Core.s

# target to generate assembly for a file
ecs/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/Core.cpp.s
.PHONY : ecs/Core.cpp.s

ecs/Entity.o: ecs/Entity.cpp.o
.PHONY : ecs/Entity.o

# target to build an object file
ecs/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/Entity.cpp.o
.PHONY : ecs/Entity.cpp.o

ecs/Entity.i: ecs/Entity.cpp.i
.PHONY : ecs/Entity.i

# target to preprocess a source file
ecs/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/Entity.cpp.i
.PHONY : ecs/Entity.cpp.i

ecs/Entity.s: ecs/Entity.cpp.s
.PHONY : ecs/Entity.s

# target to generate assembly for a file
ecs/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/Entity.cpp.s
.PHONY : ecs/Entity.cpp.s

ecs/Scene.o: ecs/Scene.cpp.o
.PHONY : ecs/Scene.o

# target to build an object file
ecs/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/Scene.cpp.o
.PHONY : ecs/Scene.cpp.o

ecs/Scene.i: ecs/Scene.cpp.i
.PHONY : ecs/Scene.i

# target to preprocess a source file
ecs/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/Scene.cpp.i
.PHONY : ecs/Scene.cpp.i

ecs/Scene.s: ecs/Scene.cpp.s
.PHONY : ecs/Scene.s

# target to generate assembly for a file
ecs/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/Scene.cpp.s
.PHONY : ecs/Scene.cpp.s

ecs/SceneManager.o: ecs/SceneManager.cpp.o
.PHONY : ecs/SceneManager.o

# target to build an object file
ecs/SceneManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/SceneManager.cpp.o
.PHONY : ecs/SceneManager.cpp.o

ecs/SceneManager.i: ecs/SceneManager.cpp.i
.PHONY : ecs/SceneManager.i

# target to preprocess a source file
ecs/SceneManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/SceneManager.cpp.i
.PHONY : ecs/SceneManager.cpp.i

ecs/SceneManager.s: ecs/SceneManager.cpp.s
.PHONY : ecs/SceneManager.s

# target to generate assembly for a file
ecs/SceneManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/SceneManager.cpp.s
.PHONY : ecs/SceneManager.cpp.s

ecs/components/EnemyComponent.o: ecs/components/EnemyComponent.cpp.o
.PHONY : ecs/components/EnemyComponent.o

# target to build an object file
ecs/components/EnemyComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/EnemyComponent.cpp.o
.PHONY : ecs/components/EnemyComponent.cpp.o

ecs/components/EnemyComponent.i: ecs/components/EnemyComponent.cpp.i
.PHONY : ecs/components/EnemyComponent.i

# target to preprocess a source file
ecs/components/EnemyComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/EnemyComponent.cpp.i
.PHONY : ecs/components/EnemyComponent.cpp.i

ecs/components/EnemyComponent.s: ecs/components/EnemyComponent.cpp.s
.PHONY : ecs/components/EnemyComponent.s

# target to generate assembly for a file
ecs/components/EnemyComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/EnemyComponent.cpp.s
.PHONY : ecs/components/EnemyComponent.cpp.s

ecs/components/HealthComponent.o: ecs/components/HealthComponent.cpp.o
.PHONY : ecs/components/HealthComponent.o

# target to build an object file
ecs/components/HealthComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/HealthComponent.cpp.o
.PHONY : ecs/components/HealthComponent.cpp.o

ecs/components/HealthComponent.i: ecs/components/HealthComponent.cpp.i
.PHONY : ecs/components/HealthComponent.i

# target to preprocess a source file
ecs/components/HealthComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/HealthComponent.cpp.i
.PHONY : ecs/components/HealthComponent.cpp.i

ecs/components/HealthComponent.s: ecs/components/HealthComponent.cpp.s
.PHONY : ecs/components/HealthComponent.s

# target to generate assembly for a file
ecs/components/HealthComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/HealthComponent.cpp.s
.PHONY : ecs/components/HealthComponent.cpp.s

ecs/components/PlayerComponent.o: ecs/components/PlayerComponent.cpp.o
.PHONY : ecs/components/PlayerComponent.o

# target to build an object file
ecs/components/PlayerComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/PlayerComponent.cpp.o
.PHONY : ecs/components/PlayerComponent.cpp.o

ecs/components/PlayerComponent.i: ecs/components/PlayerComponent.cpp.i
.PHONY : ecs/components/PlayerComponent.i

# target to preprocess a source file
ecs/components/PlayerComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/PlayerComponent.cpp.i
.PHONY : ecs/components/PlayerComponent.cpp.i

ecs/components/PlayerComponent.s: ecs/components/PlayerComponent.cpp.s
.PHONY : ecs/components/PlayerComponent.s

# target to generate assembly for a file
ecs/components/PlayerComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/PlayerComponent.cpp.s
.PHONY : ecs/components/PlayerComponent.cpp.s

ecs/components/PositionComponent.o: ecs/components/PositionComponent.cpp.o
.PHONY : ecs/components/PositionComponent.o

# target to build an object file
ecs/components/PositionComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/PositionComponent.cpp.o
.PHONY : ecs/components/PositionComponent.cpp.o

ecs/components/PositionComponent.i: ecs/components/PositionComponent.cpp.i
.PHONY : ecs/components/PositionComponent.i

# target to preprocess a source file
ecs/components/PositionComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/PositionComponent.cpp.i
.PHONY : ecs/components/PositionComponent.cpp.i

ecs/components/PositionComponent.s: ecs/components/PositionComponent.cpp.s
.PHONY : ecs/components/PositionComponent.s

# target to generate assembly for a file
ecs/components/PositionComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/PositionComponent.cpp.s
.PHONY : ecs/components/PositionComponent.cpp.s

ecs/components/RotationComponent.o: ecs/components/RotationComponent.cpp.o
.PHONY : ecs/components/RotationComponent.o

# target to build an object file
ecs/components/RotationComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/RotationComponent.cpp.o
.PHONY : ecs/components/RotationComponent.cpp.o

ecs/components/RotationComponent.i: ecs/components/RotationComponent.cpp.i
.PHONY : ecs/components/RotationComponent.i

# target to preprocess a source file
ecs/components/RotationComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/RotationComponent.cpp.i
.PHONY : ecs/components/RotationComponent.cpp.i

ecs/components/RotationComponent.s: ecs/components/RotationComponent.cpp.s
.PHONY : ecs/components/RotationComponent.s

# target to generate assembly for a file
ecs/components/RotationComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/RotationComponent.cpp.s
.PHONY : ecs/components/RotationComponent.cpp.s

ecs/components/ScaleComponent.o: ecs/components/ScaleComponent.cpp.o
.PHONY : ecs/components/ScaleComponent.o

# target to build an object file
ecs/components/ScaleComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/ScaleComponent.cpp.o
.PHONY : ecs/components/ScaleComponent.cpp.o

ecs/components/ScaleComponent.i: ecs/components/ScaleComponent.cpp.i
.PHONY : ecs/components/ScaleComponent.i

# target to preprocess a source file
ecs/components/ScaleComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/ScaleComponent.cpp.i
.PHONY : ecs/components/ScaleComponent.cpp.i

ecs/components/ScaleComponent.s: ecs/components/ScaleComponent.cpp.s
.PHONY : ecs/components/ScaleComponent.s

# target to generate assembly for a file
ecs/components/ScaleComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/ScaleComponent.cpp.s
.PHONY : ecs/components/ScaleComponent.cpp.s

ecs/components/ShootComponent.o: ecs/components/ShootComponent.cpp.o
.PHONY : ecs/components/ShootComponent.o

# target to build an object file
ecs/components/ShootComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/ShootComponent.cpp.o
.PHONY : ecs/components/ShootComponent.cpp.o

ecs/components/ShootComponent.i: ecs/components/ShootComponent.cpp.i
.PHONY : ecs/components/ShootComponent.i

# target to preprocess a source file
ecs/components/ShootComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/ShootComponent.cpp.i
.PHONY : ecs/components/ShootComponent.cpp.i

ecs/components/ShootComponent.s: ecs/components/ShootComponent.cpp.s
.PHONY : ecs/components/ShootComponent.s

# target to generate assembly for a file
ecs/components/ShootComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/ShootComponent.cpp.s
.PHONY : ecs/components/ShootComponent.cpp.s

ecs/components/VelocityComponent.o: ecs/components/VelocityComponent.cpp.o
.PHONY : ecs/components/VelocityComponent.o

# target to build an object file
ecs/components/VelocityComponent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/VelocityComponent.cpp.o
.PHONY : ecs/components/VelocityComponent.cpp.o

ecs/components/VelocityComponent.i: ecs/components/VelocityComponent.cpp.i
.PHONY : ecs/components/VelocityComponent.i

# target to preprocess a source file
ecs/components/VelocityComponent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/VelocityComponent.cpp.i
.PHONY : ecs/components/VelocityComponent.cpp.i

ecs/components/VelocityComponent.s: ecs/components/VelocityComponent.cpp.s
.PHONY : ecs/components/VelocityComponent.s

# target to generate assembly for a file
ecs/components/VelocityComponent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/components/VelocityComponent.cpp.s
.PHONY : ecs/components/VelocityComponent.cpp.s

ecs/system/ASystem.o: ecs/system/ASystem.cpp.o
.PHONY : ecs/system/ASystem.o

# target to build an object file
ecs/system/ASystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/ASystem.cpp.o
.PHONY : ecs/system/ASystem.cpp.o

ecs/system/ASystem.i: ecs/system/ASystem.cpp.i
.PHONY : ecs/system/ASystem.i

# target to preprocess a source file
ecs/system/ASystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/ASystem.cpp.i
.PHONY : ecs/system/ASystem.cpp.i

ecs/system/ASystem.s: ecs/system/ASystem.cpp.s
.PHONY : ecs/system/ASystem.s

# target to generate assembly for a file
ecs/system/ASystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/ASystem.cpp.s
.PHONY : ecs/system/ASystem.cpp.s

ecs/system/AudioSystem.o: ecs/system/AudioSystem.cpp.o
.PHONY : ecs/system/AudioSystem.o

# target to build an object file
ecs/system/AudioSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/AudioSystem.cpp.o
.PHONY : ecs/system/AudioSystem.cpp.o

ecs/system/AudioSystem.i: ecs/system/AudioSystem.cpp.i
.PHONY : ecs/system/AudioSystem.i

# target to preprocess a source file
ecs/system/AudioSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/AudioSystem.cpp.i
.PHONY : ecs/system/AudioSystem.cpp.i

ecs/system/AudioSystem.s: ecs/system/AudioSystem.cpp.s
.PHONY : ecs/system/AudioSystem.s

# target to generate assembly for a file
ecs/system/AudioSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/AudioSystem.cpp.s
.PHONY : ecs/system/AudioSystem.cpp.s

ecs/system/EventSystem.o: ecs/system/EventSystem.cpp.o
.PHONY : ecs/system/EventSystem.o

# target to build an object file
ecs/system/EventSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/EventSystem.cpp.o
.PHONY : ecs/system/EventSystem.cpp.o

ecs/system/EventSystem.i: ecs/system/EventSystem.cpp.i
.PHONY : ecs/system/EventSystem.i

# target to preprocess a source file
ecs/system/EventSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/EventSystem.cpp.i
.PHONY : ecs/system/EventSystem.cpp.i

ecs/system/EventSystem.s: ecs/system/EventSystem.cpp.s
.PHONY : ecs/system/EventSystem.s

# target to generate assembly for a file
ecs/system/EventSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/EventSystem.cpp.s
.PHONY : ecs/system/EventSystem.cpp.s

ecs/system/GameSystem.o: ecs/system/GameSystem.cpp.o
.PHONY : ecs/system/GameSystem.o

# target to build an object file
ecs/system/GameSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/GameSystem.cpp.o
.PHONY : ecs/system/GameSystem.cpp.o

ecs/system/GameSystem.i: ecs/system/GameSystem.cpp.i
.PHONY : ecs/system/GameSystem.i

# target to preprocess a source file
ecs/system/GameSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/GameSystem.cpp.i
.PHONY : ecs/system/GameSystem.cpp.i

ecs/system/GameSystem.s: ecs/system/GameSystem.cpp.s
.PHONY : ecs/system/GameSystem.s

# target to generate assembly for a file
ecs/system/GameSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/GameSystem.cpp.s
.PHONY : ecs/system/GameSystem.cpp.s

ecs/system/GraphicSystem.o: ecs/system/GraphicSystem.cpp.o
.PHONY : ecs/system/GraphicSystem.o

# target to build an object file
ecs/system/GraphicSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/GraphicSystem.cpp.o
.PHONY : ecs/system/GraphicSystem.cpp.o

ecs/system/GraphicSystem.i: ecs/system/GraphicSystem.cpp.i
.PHONY : ecs/system/GraphicSystem.i

# target to preprocess a source file
ecs/system/GraphicSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/GraphicSystem.cpp.i
.PHONY : ecs/system/GraphicSystem.cpp.i

ecs/system/GraphicSystem.s: ecs/system/GraphicSystem.cpp.s
.PHONY : ecs/system/GraphicSystem.s

# target to generate assembly for a file
ecs/system/GraphicSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/GraphicSystem.cpp.s
.PHONY : ecs/system/GraphicSystem.cpp.s

ecs/system/ParticleSystem.o: ecs/system/ParticleSystem.cpp.o
.PHONY : ecs/system/ParticleSystem.o

# target to build an object file
ecs/system/ParticleSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/ParticleSystem.cpp.o
.PHONY : ecs/system/ParticleSystem.cpp.o

ecs/system/ParticleSystem.i: ecs/system/ParticleSystem.cpp.i
.PHONY : ecs/system/ParticleSystem.i

# target to preprocess a source file
ecs/system/ParticleSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/ParticleSystem.cpp.i
.PHONY : ecs/system/ParticleSystem.cpp.i

ecs/system/ParticleSystem.s: ecs/system/ParticleSystem.cpp.s
.PHONY : ecs/system/ParticleSystem.s

# target to generate assembly for a file
ecs/system/ParticleSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/ecs/system/ParticleSystem.cpp.s
.PHONY : ecs/system/ParticleSystem.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MySFMLProject.dir/build.make CMakeFiles/MySFMLProject.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MySFMLProject"
	@echo "... ecs/AComponent.o"
	@echo "... ecs/AComponent.i"
	@echo "... ecs/AComponent.s"
	@echo "... ecs/Core.o"
	@echo "... ecs/Core.i"
	@echo "... ecs/Core.s"
	@echo "... ecs/Entity.o"
	@echo "... ecs/Entity.i"
	@echo "... ecs/Entity.s"
	@echo "... ecs/Scene.o"
	@echo "... ecs/Scene.i"
	@echo "... ecs/Scene.s"
	@echo "... ecs/SceneManager.o"
	@echo "... ecs/SceneManager.i"
	@echo "... ecs/SceneManager.s"
	@echo "... ecs/components/EnemyComponent.o"
	@echo "... ecs/components/EnemyComponent.i"
	@echo "... ecs/components/EnemyComponent.s"
	@echo "... ecs/components/HealthComponent.o"
	@echo "... ecs/components/HealthComponent.i"
	@echo "... ecs/components/HealthComponent.s"
	@echo "... ecs/components/PlayerComponent.o"
	@echo "... ecs/components/PlayerComponent.i"
	@echo "... ecs/components/PlayerComponent.s"
	@echo "... ecs/components/PositionComponent.o"
	@echo "... ecs/components/PositionComponent.i"
	@echo "... ecs/components/PositionComponent.s"
	@echo "... ecs/components/RotationComponent.o"
	@echo "... ecs/components/RotationComponent.i"
	@echo "... ecs/components/RotationComponent.s"
	@echo "... ecs/components/ScaleComponent.o"
	@echo "... ecs/components/ScaleComponent.i"
	@echo "... ecs/components/ScaleComponent.s"
	@echo "... ecs/components/ShootComponent.o"
	@echo "... ecs/components/ShootComponent.i"
	@echo "... ecs/components/ShootComponent.s"
	@echo "... ecs/components/VelocityComponent.o"
	@echo "... ecs/components/VelocityComponent.i"
	@echo "... ecs/components/VelocityComponent.s"
	@echo "... ecs/system/ASystem.o"
	@echo "... ecs/system/ASystem.i"
	@echo "... ecs/system/ASystem.s"
	@echo "... ecs/system/AudioSystem.o"
	@echo "... ecs/system/AudioSystem.i"
	@echo "... ecs/system/AudioSystem.s"
	@echo "... ecs/system/EventSystem.o"
	@echo "... ecs/system/EventSystem.i"
	@echo "... ecs/system/EventSystem.s"
	@echo "... ecs/system/GameSystem.o"
	@echo "... ecs/system/GameSystem.i"
	@echo "... ecs/system/GameSystem.s"
	@echo "... ecs/system/GraphicSystem.o"
	@echo "... ecs/system/GraphicSystem.i"
	@echo "... ecs/system/GraphicSystem.s"
	@echo "... ecs/system/ParticleSystem.o"
	@echo "... ecs/system/ParticleSystem.i"
	@echo "... ecs/system/ParticleSystem.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

