name: CI/CD for C++ Project

on:
  push:
    branches:
      - main  # Change 'main' to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ClangFormat
      run: |
        sudo apt-get update
        sudo apt-get install clang-format
      shell: bash

    - name: Format code with ClangFormat
      run: |
        clang-format -i -style=file $(find . -name "*.cpp" -o -name "*.h")
      shell: bash

    - name: Compile C++ code
      run: |
        mkdir build
        cd build
        cmake ..
        make
      working-directory: ${{ github.workspace }}

    - name: Check Doxygen documentation
      run: |
        doxygen -n Doxyfile
        doxygen
      working-directory: ${{ github.workspace }}
