name: ci

on: [push, pull_request]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-CPP-500-TLS-5-1-rtype-saad.berrada.git

  



jobs:
  cmake_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          chmod +x install.sh
          ./install.sh
      

  include_doxygen_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen

      - name: Generate Documentation
        run: |
          # Generate documentation using Doxygen
          ./doc.sh
      - name: Check Documentation
        run: |
          # Check if the Doxygen generation produced any warnings or errors
          if [ -n "$(grep -E '(warning|error)' ../../doc/doxygen_warnings.log)" ]; then
            echo "Doxygen generated warnings or errors. Please check the documentation."
            exit 1
          fi

  include_clang_format_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Clang Format
        run: |
          sudo apt-get update
          sudo apt-get install clang-format
          
      - name: Format Code
        run: |
          # Format all C++ files in the repository
          find . -name "*.cpp" -o -name "*.hpp" | xargs clang-format -i

      - name: Commit Changes
        run: |
          git config --local user.email "mangasteak@gmail.com"
          git config --local user.name "CI Bot"
          git add .
          git diff-index --quiet HEAD || git commit -m "Apply clang-format"
          
  display_compilation_error:
    runs-on: ubuntu-latest
    needs: cmake_build
    steps:
      - name: Display Compilation Error
        run: |
          # Check if compilation produced any errors
          if [ -n "$(grep -i 'error' build.log)" ]; then
          echo "Compilation errors detected:"
          grep -i 'error' build.log
          exit 1
          else
            echo "No compilation errors detected."
          fi
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check good files & folders
        run: |
          paths=($(find . -name '#*#' -o -name '*-' -o -name '*.tmp' -o -name '*.o' -o -name '*.a' -o -name '*.so' -o -name '*.gcno' -o -name '*.gcda' -o -name '*.gcov' -o -type d -name 'tmp'))
          if [[ ! -z "$paths" ]]; then
            IFS=$'\n'
            for FILE in "${paths[@]}"; do echo "::error title=Unwanted file detected,file=$FILE::$FILE"; done
            unset IFS
            exit 1
          fi

  push_to_mirror:
    needs: [check_repository_cleanliness, display_compilation_error, include_clang_format_check, include_doxygen_check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
